name: Build and Release

on:
  push:
    branches:
      - main
    tags:
      - "*"
    paths-ignore:
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      GITHUB_OAUTH: ${{ secrets.OAUTH_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package And Release
        uses: BigWigsMods/packager@master